change to 81ba0922ae8c1b430f503f55a7c9f281c9733038 to fix ioctl.c issue
./ioctl.c:1127:3: error: positional initialization of field in 'struct'
declared with 'designated_init' attribute [-Werror=designated-init]

Signed-off-by: Changming Huang <jerry.huang@nxp.com>