e2fsprogs: upgrade to 1.44.2
When running buildroot version on ubuntu-18.04 with e2fsgrops v1.43.3 version,
below error observered, so upgrade to 1.44.2 to fix this issue.

./../misc/create_inode.c: At top level:
./../misc/create_inode.c:399:18: error: conflicting types for ‘copy_file_range’
 static errcode_t copy_file_range(ext2_filsys fs, int fd, ext2_file_t e2_file,
                  ^~~~~~~~~~~~~~~
In file included from ./../misc/create_inode.c:19:0:
/usr/include/unistd.h:1110:9: note: previous declaration of ‘copy_file_range’ was here
 ssize_t copy_file_range (int __infd, __off64_t *__pinoff,

Signed-off-by: Changnming Huang <jerry.huang@nxp.com>